development:
  adapter: mysql2
  encoding: utf8
  database: srs_demo_development
  username: root
 #password: 
  port: 3306
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: srs_demo_test
  username: root
  # password: 
  port: 3306
  host: localhost

staging:
  adapter: mysql2
  encoding: utf8
  database: srs_demo_staging
  username: root
  # password: 
  port: 3306
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: srs_demo_production
  username: root
  # password: 
  port: 3306
  host: localhost