development:
  adapter: postgresql
  encoding: unicode
  username: root
  password: root
  pool: 5
  timeout: 5000
  host: localhost
  database: auth_client_api_development
test:
  adapter: postgresql
  encoding: unicode
  username: root
  password: root
  pool: 5
  timeout: 5000
  host: localhost
  database: auth_client_api_test
production:
  adapter: postgresql
  encoding: unicode
  username: 
  password: 
  pool: 5
  timeout: 5000
  host: localhost
  database: auth_client_api_production